FROM --platform=linux/amd64 ubuntu:22.04

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install necessary packages and tools
RUN DEBIAN_FRONTEND=noninteractive  \
    apt-get update && apt-get install -y \
    curl \
    openjdk-17-jdk \
    unzip \
    zip \
    git \
    software-properties-common \
    python3-pip && \ 
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && apt-get install -y \
    python3.9  \
    python3.9-distutils \
    python3.9-venv \
    python3.10  \
    python3.10-distutils \
    python3.10-venv \
    python3.11  \
    python3.12  \
    python3.13  \
    tox \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1

# ARG USERNAME=mleap
# ARG USER_UID=1001
# ARG USER_GID=$USER_UID

# # Create the user
# RUN (groupadd --gid $USER_GID $USERNAME || true) \
#     && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME --shell /usr/bin/bash

# USER $USERNAME

# Install SDKMAN and Scala
SHELL ["/bin/bash", "-c"]

RUN curl -s "https://get.sdkman.io" | bash \
    && source "$HOME/.sdkman/bin/sdkman-init.sh" \
    && sdk install scala 2.13.16 \
    && sdk install sbt

# Set up your environment as needed
